### ISSUE TITLE
ValueError: [timestamp] is not exist in interaction [The batch_size of interaction: 7813737 or time_field not set 

### ISSUE THREAD

**Issue by hardzal** [amrohendawi/BERT4Rec#1]
getting errors when using anime datasets, How to train anime datasets? there is no timestamp column, thank you

**Comment by amrohendawi** [comment]
You are right. There is no timestamp column. To fix this you can modify the Anime Class in `recSys_framework/dataset_preprocessing/Dataset.py` to add an artificial timestamp column like an enumerated index.

Here are basic steps to prepare the anime dataset:

1. Download the dataset from [kaggle](https://www.kaggle.com/datasets/CooperUnion/anime-recommendations-database)
2. Unpack it in the following directory `recSys_framework/datasets/anime`
3. Modify the Anime Class in `recSys_framework/dataset_preprocessing/Dataset.py`
4. Convert the dataset into atomic format:

 ```bash
~/recSys_framework$ python preprocess_dataset.py --dataset anime  --convert_inter --convert_item --convert_user
100%|███████████████████████████████████████████████████| 7813737/7813737 [12:01<00:00, 10834.36it/s]
100%|█████████████████████████████████████████████████████| 12294/12294 [00:02<00:00, 5902.73it/s]
This dataset can't be converted to user file
 ```
 

Check out the [notebooks list](https://www.kaggle.com/datasets/CooperUnion/anime-recommendations-database/code) under the dataset in Kaggle for some additional inspiration.
